# Generated by Django 6.1.1 on 2026-09-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('mock', 'Mock Provider (Offline Development & Testing)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('google', 'Google Gemini'), ('custom', 'Custom HTTP Endpoint / Local Ollama')], default='mock', max_length=50)),
                ('base_url', models.CharField(blank=True, default='', help_text='API Endpoint URL (if applicable)', max_length=255)),
                ('api_key_env_var', models.CharField(blank=True, default='', help_text='Environment variable name storing secret API key (e.g. OPENAI_API_KEY)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human readable model title', max_length=150)),
                ('model_identifier', models.CharField(help_text='Exact API model string e.g. gpt-4o, mock-accurate-v1', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('temperature', models.FloatField(default=0.0)),
                ('max_tokens', models.IntegerField(default=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='models_registry.modelprovider')),
            ],
            options={
                'ordering': ['provider', 'name'],
                'unique_together': {('provider', 'model_identifier')},
            },
        ),
    ]
