# Generated by Django 6.1.1 on 2026-09-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benchmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Error Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_match_score', models.FloatField(default=0.0)),
                ('semantic_similarity_score', models.FloatField(default=0.0)),
                ('factuality_score', models.FloatField(default=0.0)),
                ('citation_score', models.FloatField(default=0.0)),
                ('composite_score', models.FloatField(default=0.0)),
                ('is_hallucination', models.BooleanField(default=False)),
                ('is_abstained', models.BooleanField(default=False)),
                ('is_correct_abstention', models.BooleanField(default=False)),
                ('evaluator_reasoning', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_categories', models.ManyToManyField(blank=True, related_name='evaluations', to='evaluations.errorcategory')),
                ('model_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='benchmarks.modelresponse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField()),
                ('status', models.CharField(choices=[('supported', 'Supported by Reference'), ('unsupported', 'Unsupported Claim'), ('contradicted', 'Contradicts Reference'), ('unverifiable', 'Unverifiable / Citation Error')], default='supported', max_length=30)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=1.0)),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='evaluations.evaluationresult')),
            ],
        ),
    ]
